drop table if exists sa_HojaDieta; # HojaDieta
drop table if exists sa_OP; # OrdenProduccion
drop table if exists sa_Empresa; # OrdenProduccion

create table if not exists sa_Empresa(
`EmpresaId` int primary key auto_increment,
`NombreEmpresa` varchar(50),
`Estado` enum('Inactivo', 'Activo', 'Finalizada') default 'Activo',
`CreatedBy` varchar(20) DEFAULT '',
`CreatedAt` timestamp DEFAULT current_timestamp,
`ModifiedBy` varchar(20) DEFAULT '',
`ModifiedAt` datetime,
INDEX(`EmpresaId`));

create table if not exists sa_OP(
`OPId` int primary key auto_increment,
`Fecha` datetime,
`NombreSolicita` varchar(20),
`CargoSolicita` varchar(20),
`USolicitaId` int,
`Servicio` varchar(50),
`SECTOR` varchar(10),
`NombreEmpresa` varchar(50),
`EmpresaId` int,
`HDId` int,
`DistribucionId` int,
`Estado` enum('Inactivo', 'Activo', 'Finalizada') default 'Activo',
`CreatedBy` varchar(20) DEFAULT '',
`CreatedAt` timestamp DEFAULT current_timestamp,
`ModifiedBy` varchar(20) DEFAULT '',
`ModifiedAt` datetime,
foreign key(USolicitaId) references usuario(UsuarioId),
foreign key(HDId) references sa_hd(HDId),
foreign key(EmpresaId) references sa_Empresa(EmpresaId),
INDEX(`OPId`, `DistribucionId`, `EmpresaId`));

create table if not exists sa_HojaDieta(
`DOPId` int primary key auto_increment,
`DHDId` int,
`Fecha` datetime,
`HABCAMA` varchar(20) DEFAULT '',
`NOADMISION` varchar(20) DEFAULT '',
`IDAFILIADO` varchar(20) DEFAULT '',
`NOMBREAFI` varchar(150) DEFAULT '',
`TIPOESTANCIA` varchar(150) DEFAULT '',
`IDTERCERO` varchar(15) DEFAULT '',
`RAZONSOCIAL` varchar(150) DEFAULT '',
`SEXO` varchar(10) DEFAULT '',
`HDId` int,
`Desayuno` varchar(10),
`DesayunoId` int default null,
`EDesayunoId` int default null,
`MM` varchar(10),
`MMId` int default null,
`EMMId` int default null,
`Almuerzo` varchar(10),
`AlmuerzoId` int default null,
`EAlmuerzoId` int default null,
`MT` varchar(10),
`MTId` int default null,
`EMTId` int default null,
`Cena` varchar(10),
`CenaId` int default null,
`ECenaId` int default null,
`MC` varchar(10),
`MCId` int default null,
`EMCId` int default null,
`Estado` enum('Inactivo', 'Activo', 'Finalizada') default 'Activo',
`CreatedBy` varchar(20) DEFAULT '',
`CreatedAt` timestamp DEFAULT current_timestamp,
`ModifiedBy` varchar(20) DEFAULT '',
`ModifiedAt` datetime,
foreign key(HDId) references sa_hd(HDId),
foreign key(DHDId) references sa_dhd(DHDId),
foreign key(EDesayunoId) references sa_Empresa(EmpresaId),
foreign key(EMMId) references sa_Empresa(EmpresaId),
foreign key(EAlmuerzoId) references sa_Empresa(EmpresaId),
foreign key(EMTId) references sa_Empresa(EmpresaId),
foreign key(EAlmuerzoId) references sa_Empresa(EmpresaId),
foreign key(ECenaId) references sa_Empresa(EmpresaId),
foreign key(DesayunoId) references sa_var(VariableId),
foreign key(MMId) references sa_var(VariableId),
foreign key(AlmuerzoId) references sa_var(VariableId),
foreign key(MTId) references sa_var(VariableId),
foreign key(CenaId) references sa_var(VariableId),
foreign key(MCId) references sa_var(VariableId),
INDEX(`DOPId`, `DHDId`, `Fecha`));


