drop table if exists sst_reporte;
drop table if exists sst_hojavida;

CREATE TABLE sst_hojavida (
  HojaVidaId int(11) NOT NULL AUTO_INCREMENT,
  SedeId int(11) DEFAULT NULL,
  ServicioId int(11) DEFAULT NULL,
  Ubicacion varchar(300) DEFAULT NULL,
  Nombre varchar(100) DEFAULT NULL,
  Fabricante varchar(100) DEFAULT NULL,
  NSerial varchar(100) DEFAULT NULL,
  Tipo varchar(100) DEFAULT NULL,
  Modelo varchar(100) DEFAULT NULL,
  Sector varchar(100) DEFAULT NULL,
  ClaseExtintor varchar(100) DEFAULT NULL,
  NumeroExtintor varchar(50) DEFAULT NULL,
  RecomendacioneFabricante text,
  Foto mediumblob,
  Estado varchar(200) DEFAULT 'Activo',
  FechaInstalacion date DEFAULT NULL,
  FechaRecarga date DEFAULT NULL,
  FechaVencimiento date DEFAULT NULL,
  TipoArticulo varchar(100) DEFAULT NULL,
  CreatedBy varchar(200) DEFAULT NULL,
  CreatedAt timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedBy varchar(200) DEFAULT NULL,
  ModifiedAt datetime DEFAULT NULL,
  PRIMARY KEY (HojaVidaId),
  KEY SedeId (SedeId),
  KEY ServicioId (ServicioId),
  FOREIGN KEY (SedeId) REFERENCES sede (SedeId),
  FOREIGN KEY (ServicioId) REFERENCES servicio (ServicioId)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


create table if not exists sst_reporte(
  ReporteId int(11) NOT NULL AUTO_INCREMENT,
  NumeroReporte varchar(200) COLLATE latin1_spanish_ci DEFAULT NULL,
  SedeId int(11) DEFAULT NULL,
  FechaInspeccion date DEFAULT NULL,
  FechaRecarga date DEFAULT NULL,
  FechaVencimiento date DEFAULT NULL,
  ServicioId int(11) DEFAULT NULL,
  Ubicacion varchar(200) COLLATE latin1_spanish_ci DEFAULT NULL,
  EquipoId int(11) DEFAULT NULL,
  Acceso varchar(10) COLLATE latin1_spanish_ci DEFAULT NULL,
  Demarcacion varchar(10) COLLATE latin1_spanish_ci DEFAULT NULL,
  Senalizacion varchar(10) COLLATE latin1_spanish_ci DEFAULT NULL,
  InstalacionSitioAsignado varchar(10) COLLATE latin1_spanish_ci DEFAULT NULL,
  InstruccionesUso varchar(10) COLLATE latin1_spanish_ci DEFAULT NULL,
  AlturaAdecuada varchar(10) COLLATE latin1_spanish_ci DEFAULT NULL,
  Corneta varchar(10) COLLATE latin1_spanish_ci DEFAULT NULL,
  Manguera varchar(10) COLLATE latin1_spanish_ci DEFAULT NULL,
  CargaExtintor varchar(10) COLLATE latin1_spanish_ci DEFAULT NULL,
  ManijaTransporte varchar(10) COLLATE latin1_spanish_ci DEFAULT NULL,
  ManijaDescarga varchar(10) COLLATE latin1_spanish_ci DEFAULT NULL,
  Pasador varchar(10) COLLATE latin1_spanish_ci DEFAULT NULL,
  SelloSeguridad varchar(10) COLLATE latin1_spanish_ci DEFAULT NULL,
  Observacion text COLLATE latin1_spanish_ci,
  Responsable varchar(200) COLLATE latin1_spanish_ci DEFAULT NULL,
  Estado varchar(200) COLLATE latin1_spanish_ci DEFAULT 'Borrador',
  CreatedBy varchar(200) COLLATE latin1_spanish_ci DEFAULT NULL,
  CreatedAt timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ModifiedBy varchar(200) COLLATE latin1_spanish_ci DEFAULT NULL,
  ModifiedAt datetime DEFAULT NULL,
  EstadoReporte varchar(45) COLLATE latin1_spanish_ci DEFAULT 'Activo',
  PRIMARY KEY (ReporteId),
  KEY ServicioId (ServicioId),
  KEY SedeId (SedeId),
  KEY EquipoId (EquipoId),
  FOREIGN KEY (ServicioId) REFERENCES servicio (ServicioId),
  FOREIGN KEY (SedeId) REFERENCES sede (SedeId),
  FOREIGN KEY (EquipoId) REFERENCES sst_hojavida (HojaVidaId)
) ENGINE=InnoDB;